# Generated by Django 3.0.8 on 2020-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='age',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reason',
            name='email',
            field=models.EmailField(default='new@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reason',
            name='ethnicity',
            field=models.CharField(default='no', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reason',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='M', max_length=2),
        ),
        migrations.AddField(
            model_name='reason',
            name='reason_keywords',
            field=models.CharField(default='no', help_text='Please enter the keywords that describe your choice in not more than 10 words.', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reason',
            name='video_type',
            field=models.CharField(choices=[('R', 'Real'), ('F', 'Fake'), ('U', 'Unsure')], default='R', max_length=2),
        ),
    ]
